// src/components/Cart/AddToCartForm.tsx
import { isCartOpen, addCartItem } from '../../stores/cartStore';
import type { CartItemDisplayInfo } from '../../stores/cartStore';
import type { ComponentChildren } from 'preact';

type Props = {
	item: CartItemDisplayInfo;
	children: ComponentChildren;
};

export default function AddToCartForm({ item, children }: Props) {
	function addToCart(e: SubmitEvent) {
		e.preventDefault();
		isCartOpen.set(true);
		addCartItem(item);
	}

	return <form onSubmit={addToCart}>{children}</form>;
}

// ssrc/components/Cart/AddToCartForm.vue
<template>
	<form @submit="addToCart">
	  <slot></slot>
	</form>
  </template>
  
  <script setup>
	import { addCartItem, isCartOpen } from '../../stores/cartStore';
  
	// we'll hardcode the item info for simplicity!
	const hardcodedItemInfo = {
	  id: 'astronaut-figurine',
	  name: 'Astronaut Figurine',
	  imageSrc: '/images/chococake.jpg',
	}
  
	function addToCart(e) {
	  e.preventDefault();
	  isCartOpen.set(true);
	  addCartItem(hardcodedItemInfo);
	}
  </script>
